#!/usr/bin/env bash

## programs

alias keepassx="keepassx ~/Documents/.private/database.kdbx"

## shortcuts

alias q=" exit"
alias t="tmux"
alias s="subl"
alias sa="subl -a"

alias sl=ls
alias ls="ls -G"        # Compact view, show colors
alias la="ls -AF"       # Compact view, show hidden
alias ll="ls -al"
alias l="ls -a"
alias l1="ls -1"

alias c="clear"
alias cls="clear"

alias edit="$EDITOR"
alias e="$EDITOR"

alias q="exit"

alias ..="cd .."          # Go up one directory
alias ...="cd ../.."      # Go up two directories
alias ....="cd ../../.."  # Go up three directories
alias -- -="cd -"         # Go back

alias h="history"


## directory creation
alias md="mkdir -p"
alias rd="rmdir"


# configuration
alias grep="grep --color=auto"
alias ls="ls --color=auto"

## system management

alias reboot="sudo systemctl reboot"
alias systemctl="sudo systemctl"
alias netctl="sudo netctl"
